apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      meshExpansion:
        enabled: true
      multiCluster:
        enabled: true
        clusterName: control
      network: control-net

      meshNetworks:
        control-net:
          endpoints:
          - fromRegistry: control
          gateways:
          - registry_service_name: istio-ingressgateway.istio-system.svc.cluster.local
            port: 443

# don't put any actual value after this line
