apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  values:
    global:
      multiCluster:
        enabled: true
        clusterName: DATA_PLANE_NAME
      network: DATA_PLANE_NAME-net

      remotePilotAddress: ISTIOD_REMOTE_EP