apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  components: 
    base: 
      enabled: true 
    istiodRemote: 
      enabled: true
    pilot:
      enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  values:
    global:
      jwtPolicy: first-party-jwt
      multiCluster:
        enabled: true
        clusterName: DATA_PLANE_NAME
      network: DATA_PLANE_NAME-net

      centralIstiod: true
      remotePilotAddress: ISTIOD_REMOTE_EP
