apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-reader-istio-system
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - '*'
  verbs:
  - create
  - update
