apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- .data-plane-pre.yaml


patchesStrategicMerge:
- clusterrole.yaml
- validatingwebhook.yaml
- .endpoints.yaml
- .service.yaml
- .mutatingwebhook.yaml
