apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: ISTIO_NAMESPACE
spec:
  clusterIP: None
  ports:
  - name: tcp-istiod
    port: 15012
    targetPort: 15012
  - name: tcp-istiowebhook
    port: 15017
    targetPort: 15017